development:
    adapter: postgresql
    encoding: unicode
    database: jdtai_development
    pool: 5
    username: postgres
    password: postgres

test:
    adapter: postgresql
    encoding: unicode
    database: jdtai_test
    pool: 5
    username: postgres
    password: postgres
